#!/bin/bash

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIRjdk1.7.0_75
export M2=$OPENSHIFT_DATA_DIRapache-maven-2.2.1/bin
export PATH=$JAVA_HOME/bin:$M2:$PATH



cd $OPENSHIFT_REPO_DIR

mvn -e -s $OPENSHIFT_REPO_DIR.openshift/settings.xml -q install:install-file -Dfile=$OPENSHIFT_REPO_DIRsrc/main/resources/db/db4o-8.0.160.14822.jar -DgroupId=com.project.db4o -DartifactId=db4o -Dversion=1.0 -Dpackaging=jar
mvn -e -s $OPENSHIFT_REPO_DIR.openshift/settings.xml -q clean package
