#!/bin/bash

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR jdk1.7.0_75
export M2=$OPENSHIFT_DATA_DIR apache-maven-2.2.1/bin
export PATH=$JAVA_HOME/bin:$M2:$PATH



cd $OPENSHIFT_REPO_DIR

mvn -e -s $OPENSHIFT_REPO_DIR .openshift/settings.xml -q install:install-file -Dfile=../../app-root/repo/src/main/resources/db/db4o-8.0.160.14822.jar -DgroupId=com.project.db4o -DartifactId=db4o -Dversion=1.0 -Dpackaging=jar
mvn -e -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -q clean package
