#!/bin/bash

set -x

mvn -s $OPENSHIFT_REPO_DIR.openshift/settings.xml -q install:install-file --debug -Dfile=../../app-root/repo/src/main/resources/db/db4o-8.0.160.14822.jar -DgroupId=com.project.db4o -DartifactId=db4o -Dversion=1.0 -Dpackaging=jar